# Databricks config
databricks_config:
  databricks_host: "<enter your host name>"
  databricks_token: "<enter your token name>"
  databricks_clusterId: "<enter your cluster id>"
  password: "password"

# Databricks Path
pull_report:
# Databricks Path where Earning call transcripts are saved
  dbfs_pdfs_dir: "dbfs:/FileStore/investor_relations/q4_transcripts/"
# Databricks Path where llm generated reports are saved
  reports_dir: "dbfs:/FileStore/q4_2_res/"


